<a href="https://colab.research.google.com/github/amanullahshah32/Deep-Learning/blob/main/00_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
print("hello")

hello


In [26]:
!nvidia-smi

Mon Jun 24 14:00:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [27]:
import torch
print(torch.__version__)

2.3.0+cu121


In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

### creating tensors

In [29]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [30]:
scalar.ndim

0

In [31]:
# get tensor back as python int
scalar.item()

7

In [32]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [33]:
vector.ndim

1

In [34]:
vector.shape

torch.Size([2])

In [35]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [36]:
MATRIX.ndim

2

In [37]:
MATRIX[1]

tensor([ 8, 10])

In [38]:
MATRIX.shape

torch.Size([2, 2])

In [39]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [40]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

In [42]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [43]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim

(tensor([[0.6308, 0.3117, 0.5482, 0.2076],
         [0.5688, 0.7467, 0.8967, 0.9590],
         [0.8727, 0.2711, 0.5127, 0.2897]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [44]:
#create  arandom tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [45]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [46]:
#create tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

### Creating a range and tensors like

In [48]:
### torch.arange(start, end, step)

zero_to_ten_deprecated = torch.range(0,10)

<ipython-input-48-91604a08e85a>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [51]:
# create a range of values 0 to 10
zero_to_ten= torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [52]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])