<a href="https://colab.research.google.com/github/amanullahshah32/Deep-Learning/blob/main/00_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
!nvidia-smi

Tue Jul  9 17:29:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
print(torch.__version__)

2.3.0+cu121


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

### creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 8, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim

(tensor([[0.7920, 0.0964, 0.8649, 0.1374],
         [0.4037, 0.0757, 0.9491, 0.1412],
         [0.5744, 0.0065, 0.5579, 0.3876]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [20]:
#create  arandom tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
#create tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

### Creating a range and tensors like

In [23]:
### torch.arange(start, end, step)

zero_to_ten_deprecated = torch.range(0,10)

<ipython-input-23-91604a08e85a>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [24]:
# create a range of values 0 to 10
zero_to_ten= torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [27]:
# default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
# float 16 datatypes tensor
float_16_tensor = torch.tensor([3.0, 5.0, 8.0],
                               dtype = torch.float16) #torch.half would also  work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [29]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## *Manipulating Tnesors (tensor operation)*

1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

### Basic Operations

In [30]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([11,12,13])
tensor.shape

torch.Size([3])

In [31]:
# add 10 with tensor value
tensor + 10

tensor([21, 22, 23])

In [32]:
# Multiply it by 10
tensor*10

tensor([110, 120, 130])

In [33]:
# Tensor don't change unless reassigned
tensor

tensor([11, 12, 13])

Let's subtract a number and this time we'll reassign the tensor variable

In [34]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [35]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

#### PyTorch has some shortcut to perform multiplication and addition
`torch.mul()` and `torch.add()`

In [36]:
# Can also use torch functions

torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [37]:
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [38]:
torch.add(tensor, 20)

tensor([31, 32, 33])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [39]:
# Element wise multiplication (each element multiplies its equivalent)

print(tensor, '*', tensor)
print("Equals: ", tensor + tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals:  tensor([22, 24, 26])


### Matrix Multiplication


The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [40]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])


The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [41]:
# Element wise multiplication and Matrix multiplication

#Element wise multiplication
element_wise = tensor * tensor

# matrix multiplication
matrix_mul = torch.matmul(tensor, tensor)

element_wise, matrix_mul

(tensor([1, 4, 9]), tensor(14))

In [42]:
# We can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [43]:
# torch.matmul() , method is faster

# avoid operations using for looop. they are expensive

%%time

value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]

value

CPU times: user 1.81 ms, sys: 0 ns, total: 1.81 ms
Wall time: 2.38 ms


tensor(14)

In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 35.5 µs


tensor(14)

## One of the most common error in deep learning, (Shape Errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [45]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [46]:
tensor_A.shape, tensor_A.ndim,  tensor_B.shape, tensor_B.ndim

(torch.Size([3, 2]), 2, torch.Size([3, 2]), 2)

One of the ways to do this is with a *transpose* (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* `torch.transpose(input, dim0, dim1)`  - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

In [47]:
# View tensor A and B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [48]:
# View tensor A and tensor B.T
print(tensor_A.shape)
print(tensor_B.T.shape)
# here the inner dimensions are matched

torch.Size([3, 2])
torch.Size([2, 3])


In [49]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensorA= {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n ")
print(f"Multiplying: {tensor_A.shape}*{tensor_B.shape} <- inner dimensions match \n")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: ")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensorA= torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
 
Multiplying: torch.Size([3, 2])*torch.Size([3, 2]) <- inner dimensions match 

Output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 Output shape: 


You can also use torch.mm() which is a short for torch.matmul()

In [50]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### torch.nn.Linear()

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

y
=
x
⋅
A
T
+
b

Where:

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.
y is the output (a manipulation of the input in the hopes to discover patterns in it).
This is a linear function (you may have seen something like  
y
=
m
x
+
b
  in high school or elsewhere), and can be used to draw a straight line!

In [51]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [52]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible ( more on this late )
torch.manual_seed(42) # this keeps the random value same/ random values does not change if you re run this cell
linear = torch.nn.Linear(in_features = 3, # in_features = matches inner dimensions of input
                         out_features =  6) # out_features = describe outer value

x  = tensor_A.T
output = linear(x)
print(f"Input shape : {x.shape} \n")
print(f"Output shape: \n{output}\n\n Output shape: {output.shape}")

Input shape : torch.Size([2, 3]) 

Output shape: 
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

 Output shape: torch.Size([2, 6])


###  **Finding the min, max, mean, sum, etc (aggregation)**
* Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values). *

First we'll create a tensor and then find the max, min, mean and sum of it.



In [53]:
# Create a tensor
x = torch.arange(0,100, 10)
x.dtype, x

(torch.int64, tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [54]:
# lets perform some aggregation

print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
#print(f"Mean: {x.mean()}") # this is error
print(f"sum: {x.sum()}")

Minimum: 0
Maximum: 90
sum: 450


Note: You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with torch methods.

In [55]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional Min/Max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [ ]:
# Create tensor
tensor = torch.arange(10,100, 10)
print(f"Tensor: {tensor}\n")