<a href="https://colab.research.google.com/github/amanullahshah32/Deep-Learning/blob/main/00_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
print("hello")

hello


In [39]:
!nvidia-smi

Wed Jul  3 21:23:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [40]:
import torch
print(torch.__version__)

2.3.0+cu121


In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

### creating tensors

In [42]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [43]:
scalar.ndim

0

In [44]:
# get tensor back as python int
scalar.item()

7

In [45]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [46]:
vector.ndim

1

In [47]:
vector.shape

torch.Size([2])

In [48]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [49]:
MATRIX.ndim

2

In [50]:
MATRIX[1]

tensor([ 8, 10])

In [51]:
MATRIX.shape

torch.Size([2, 2])

In [52]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [53]:
TENSOR.ndim

3

In [54]:
TENSOR.shape

torch.Size([1, 3, 3])

In [55]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [56]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim

(tensor([[0.1509, 0.5678, 0.5411, 0.9213],
         [0.1272, 0.8025, 0.7569, 0.3228],
         [0.9253, 0.0970, 0.8929, 0.7338]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [57]:
#create  arandom tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [58]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [59]:
#create tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

### Creating a range and tensors like

In [60]:
### torch.arange(start, end, step)

zero_to_ten_deprecated = torch.range(0,10)

<ipython-input-60-91604a08e85a>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [61]:
# create a range of values 0 to 10
zero_to_ten= torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [62]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [64]:
# default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [65]:
# float 16 datatypes tensor
float_16_tensor = torch.tensor([3.0, 5.0, 8.0],
                               dtype = torch.float16) #torch.half would also  work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [66]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## *Manipulating Tnesors (tensor operation)*

1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

### Basic Operations

In [67]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([11,12,13])
tensor.shape

torch.Size([3])

In [68]:
# add 10 with tensor value
tensor + 10

tensor([21, 22, 23])

In [69]:
# Multiply it by 10
tensor*10

tensor([110, 120, 130])

In [70]:
# Tensor don't change unless reassigned
tensor

tensor([11, 12, 13])

Let's subtract a number and this time we'll reassign the tensor variable

In [71]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [72]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

#### PyTorch has some shortcut to perform multiplication and addition
`torch.mul()` and `torch.add()`

In [73]:
# Can also use torch functions

torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [74]:
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [75]:
torch.add(tensor, 20)

tensor([31, 32, 33])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [79]:
# Element wise multiplication (each element multiplies its equivalent)

print(tensor, '*', tensor)
print("Equals: ", tensor + tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals:  tensor([22, 24, 26])
