<a href="https://colab.research.google.com/github/amanullahshah32/Deep-Learning/blob/main/00_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
!nvidia-smi

Mon Jul  8 18:21:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
print(torch.__version__)

2.3.0+cu121


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

### creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [8, 10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 8, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim

(tensor([[0.3599, 0.3467, 0.7806, 0.3720],
         [0.1157, 0.1970, 0.8894, 0.9012],
         [0.5627, 0.9443, 0.8319, 0.6009]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [20]:
#create  arandom tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
#create tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

### Creating a range and tensors like

In [23]:
### torch.arange(start, end, step)

zero_to_ten_deprecated = torch.range(0,10)

<ipython-input-23-91604a08e85a>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [24]:
# create a range of values 0 to 10
zero_to_ten= torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [27]:
# default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
# float 16 datatypes tensor
float_16_tensor = torch.tensor([3.0, 5.0, 8.0],
                               dtype = torch.float16) #torch.half would also  work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [29]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## *Manipulating Tnesors (tensor operation)*

1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

### Basic Operations

In [30]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([11,12,13])
tensor.shape

torch.Size([3])

In [31]:
# add 10 with tensor value
tensor + 10

tensor([21, 22, 23])

In [32]:
# Multiply it by 10
tensor*10

tensor([110, 120, 130])

In [33]:
# Tensor don't change unless reassigned
tensor

tensor([11, 12, 13])

Let's subtract a number and this time we'll reassign the tensor variable

In [34]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [35]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

#### PyTorch has some shortcut to perform multiplication and addition
`torch.mul()` and `torch.add()`

In [36]:
# Can also use torch functions

torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [37]:
torch.mul(tensor, 10)

tensor([110, 120, 130])

In [38]:
torch.add(tensor, 20)

tensor([31, 32, 33])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [39]:
# Element wise multiplication (each element multiplies its equivalent)

print(tensor, '*', tensor)
print("Equals: ", tensor + tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals:  tensor([22, 24, 26])


### Matrix Multiplication


The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [40]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])


The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [41]:
# Element wise multiplication and Matrix multiplication

#Element wise multiplication
element_wise = tensor * tensor

# matrix multiplication
matrix_mul = torch.matmul(tensor, tensor)

element_wise, matrix_mul

(tensor([1, 4, 9]), tensor(14))

In [42]:
# We can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [43]:
# torch.matmul() , method is faster

# avoid operations using for looop. they are expensive

%%time

value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]

value

CPU times: user 1.14 ms, sys: 25 µs, total: 1.16 ms
Wall time: 860 µs


tensor(14)

In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 48 µs, sys: 8 µs, total: 56 µs
Wall time: 102 µs


tensor(14)

## One of the most common error in deep learning, (Shape Errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [45]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [46]:
tensor_A.shape, tensor_A.ndim,  tensor_B.shape, tensor_B.ndim

(torch.Size([3, 2]), 2, torch.Size([3, 2]), 2)

One of the ways to do this is with a *transpose* (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* `torch.transpose(input, dim0, dim1)`  - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

In [48]:
# View tensor A and B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [50]:
# View tensor A and tensor B.T
print(tensor_A.shape)
print(tensor_B.T.shape)
# here the inner dimensions are matched

torch.Size([3, 2])
torch.Size([2, 3])


In [55]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensorA= {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n ")
print(f"Multiplying: {tensor_A.shape}*{tensor_B.shape} <- inner dimensions match \n")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: ")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensorA= torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
 
Multiplying: torch.Size([3, 2])*torch.Size([3, 2]) <- inner dimensions match 

Output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 Output shape: 


You can also use torch.mm() which is a short for torch.matmul()

In [53]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])